# Generated by Django 4.1.3 on 2022-12-07 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reddit', '0002_subreddit_owner_alter_subreddit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='moderator',
            field=models.ManyToManyField(related_name='moderates_subreddit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owns_subreddit', to=settings.AUTH_USER_MODEL),
        ),
    ]
